name: Make Environment Web

on:
  push:
    branches:
      - action-create-environment
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Ingrese la URL del ambiente back al que necesita apuntar el ambiente web'
        required: true
        default: 'https://nombre-ambiente.com/'
      url_ambiente:
        description: 'Seleccione que tipo de ambiente requiere'
        required: true
        type: choice
        options:
          - Ambiente de Sandbox Web apuntando al ambiente backend anterior
          - Ambiente de Producción Web apuntando al ambiente backend anterior

jobs:
  imprimir:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v3

      - name: Reemplazar URL en el archivo de enum temporalmente
        run: |
          # Reemplazar la URL de MULTICOUNTRY por la nueva URL proporcionada
          sed -i "s|MULTICOUNTRY = '.*'|MULTICOUNTRY = '${{ github.event.inputs.nueva_url }}'|" path/to/config.ts

      - name: Mostrar archivo modificado
        run: cat config.js

      - name: Configurar git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Hacer commit y push de los cambios
        run: |
          git add config.js
          git commit -m "Actualizar URL en config.js"
          git push

      - name: Usar el archivo modificado para crear el ambiente
        run: |
          echo "Aquí puedes poner los comandos que usen el archivo modificado, como crear el ambiente"
          # Aquí puedes hacer lo que necesites con el archivo modificado

      - name: Revertir los cambios en el archivo (no subimos nada)
        run: git checkout -- config.js
