name: Make Environment Web

on:
  push:
    branches:
      - action-create-environment
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Ingrese la URL del ambiente back al que necesita apuntar el ambiente web'
        required: true
        default: 'https://nombre-ambiente.com/'
      opcion:
        description: 'Seleccione que tipo de ambiente requiere'
        required: true
        type: choice
        options:
          - Ambiente de Sandbox Web apuntando al ambiente backend anterior
          - Ambiente de Producción Web apuntando al ambiente backend anterior

jobs:
  imprimir:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo 'Mensaje ingresado 3' ${{ github.event.inputs.mensaje }}
