name: Make Environment Web

on:
  push:
    branches:
      - action-create-environment
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Escribe un mensaje'
        required: true
        default: 'Hola Mundo'

jobs:
  imprimir:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo 'Mensaje ingresado 3' ${{ github.event.inputs.mensaje }}
